/**
 * Quiz types for MCP (Model Context Protocol) quiz.
 * Questions are generated by the agent at runtime, not stored statically.
 */

export type QuizDifficulty = "easy" | "medium" | "hard";

export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
}
