import { registerAppResource, registerAppTool, RESOURCE_MIME_TYPE } from "@modelcontextprotocol/ext-apps/server";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { CallToolResult, ReadResourceResult } from "@modelcontextprotocol/sdk/types.js";
import fs from "node:fs/promises";
import path from "node:path";
import { z } from "zod";

const quizQuestionSchema = z.object({
  id: z.string(),
  question: z.string(),
  options: z.array(z.string()).min(2).max(10),
  correctIndex: z.number().int().min(0),
});

// Works both from source (server.ts) and compiled (dist/server.js)
const DIST_DIR = import.meta.filename.endsWith(".ts")
  ? path.join(import.meta.dirname, "dist")
  : import.meta.dirname;

/**
 * Creates a new MCP server instance with tools and resources registered.
 */
export function createServer(): McpServer {
  const server = new McpServer({
    name: "Basic MCP App Server (React)",
    version: "1.0.0",
  });

  // Two-part registration: tool + resource, tied together by the resource URI.
  const resourceUri = "ui://mcp-quiz/mcp-app.html";

  // Register a tool with UI metadata. When the host calls this tool, it reads
  // `_meta.ui.resourceUri` to know which resource to fetch and render as an
  // interactive UI.
  const resultsSchema = z.object({
    step: z.literal("results"),
    correctCount: z.number().int().min(0),
    totalCount: z.number().int().min(1),
    illustration: z.string().optional().describe("Image as data URL (e.g. data:image/png;base64,...) or base64 string. Generated by the agent based on quiz performance."),
  });

  registerAppTool(server,
    "mcp-quiz",
    {
      title: "MCP Quiz",
      description: "Start an interactive quiz about the Model Context Protocol (MCP). Omit args to show the difficulty picker. When the user selects a difficulty, the agent should generate new questions and call this tool with difficulty and questions. When the user completes the quiz, the UI will send the score; the agent should generate a rewarding illustration and call this tool with step 'results', correctCount, totalCount, and illustration (data URL or base64) so it appears in the quiz UI.",
      inputSchema: {
        difficulty: z
          .enum(["easy", "medium", "hard"])
          .optional()
          .describe("Quiz difficulty level. Omit to show the difficulty picker. When providing questions, set this to the selected difficulty."),
        questions: z
          .array(quizQuestionSchema)
          .optional()
          .describe("Quiz questions generated by the agent. Each question must have id, question, options (array of 2–10 strings), and correctIndex (0-based). Pass this after the user selects a difficulty so the quiz UI displays these questions."),
        step: z
          .literal("results")
          .optional()
          .describe("Set to 'results' when delivering the post-quiz reward. Requires correctCount, totalCount, and optionally illustration (image as data URL or base64)."),
        correctCount: z.number().int().min(0).optional().describe("Number of correct answers (for results step)."),
        totalCount: z.number().int().min(1).optional().describe("Total number of questions (for results step)."),
        illustration: z.string().optional().describe("Rewarding illustration image as data URL or base64. Generate based on how well the user scored."),
      },
      _meta: { ui: { resourceUri } }, // Links this tool to its UI resource
    },
    async (args: {
      difficulty?: "easy" | "medium" | "hard";
      questions?: unknown[];
      step?: "results";
      correctCount?: number;
      totalCount?: number;
      illustration?: string;
    }): Promise<CallToolResult> => {
      if (args?.step === "results" && typeof args?.correctCount === "number" && typeof args?.totalCount === "number") {
        const parsed = resultsSchema.safeParse({
          step: "results",
          correctCount: args.correctCount,
          totalCount: args.totalCount,
          illustration: args.illustration,
        });
        if (!parsed.success) {
          return {
            content: [{ type: "text", text: JSON.stringify({ error: "Invalid results format", details: parsed.error.flatten() }) }],
            isError: true,
          };
        }
        const payload = JSON.stringify(parsed.data);
        return { content: [{ type: "text", text: payload }] };
      }
      if (args?.difficulty == null && !args?.questions?.length) {
        const payload = JSON.stringify({ step: "selectDifficulty" });
        return { content: [{ type: "text", text: payload }] };
      }
      if (args?.questions != null && Array.isArray(args.questions) && args.questions.length > 0) {
        const parsed = z.array(quizQuestionSchema).safeParse(args.questions);
        if (!parsed.success) {
          return {
            content: [{ type: "text", text: JSON.stringify({ error: "Invalid questions format", details: parsed.error.flatten() }) }],
            isError: true,
          };
        }
        const payload = JSON.stringify({ questions: parsed.data });
        return { content: [{ type: "text", text: payload }] };
      }
      const payload = JSON.stringify({ step: "selectDifficulty" });
      return { content: [{ type: "text", text: payload }] };
    },
  );

  // Register the resource, which returns the bundled HTML/JavaScript for the UI.
  registerAppResource(server,
    resourceUri,
    resourceUri,
    { mimeType: RESOURCE_MIME_TYPE },
    async (): Promise<ReadResourceResult> => {
      const html = await fs.readFile(path.join(DIST_DIR, "mcp-app.html"), "utf-8");
      return {
        contents: [{ uri: resourceUri, mimeType: RESOURCE_MIME_TYPE, text: html }],
      };
    },
  );

  return server;
}
